# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:10-stretch
    working_directory: ~/repo

jobs:
  build:
    executor: my-executor

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn run lint
      - run: yarn run test:unit
      
      # build and deploy
      - run: yarn run build

      # persist the folling paths into the workspace for downstream jobs
      - persist_to_workspace:
          # must be absolute path, or relative from working directory
          root: .
          # must be relative from root
          paths:
            - dist

  deploy:
    executor: my-executor

    steps:
      - checkout
        # Firebase deploy is a development dependency
      - run: yarn install --production=false

      - attach_workspace:
          at: .
      - run:
          name: Deploy master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
